# SDK log level (off | info | debug | trace)
sdk_log_level: "info"

# Properties for Connecting to Core
core:
  server: "http://locahost:8080/kinetic"
  space_admin_credentials:
    username: "admin"
    password: "admin"
