# SDK log level (off | info | debug | trace)
sdk_log_level: "info"

# Properties for the Platform
platform:
  task_source_name: ""

# Properties for the Kinetic Request CE Source
ce:
  server: "http://localhost:8080/kinetic"
  system_credentials:
    username: "admin"
    password: "admin"
  space_admin_credentials:
    username: "kdadmin@example.com"
    password: "admin"
  space_integration_credentials:
    username: "integration.user@example.com"
    display_name: "Integration User"
  task_source_name: "Kinetic Request CE"
  filestore:
    type: "Local"
    directory: "/home/filesDirectory"
  kapps:
  export_form_data:
  export_datastore_form_data:
    - "notification-template-dates"
    - "notification-data"
  remove_data_attributes:
    - "createdAt"
    - "createdBy"
    - "updatedAt"
    - "updatedBy"
    - "closedAt"
    - "closedBy"
    - "id"
    - "authStrategy"
    - "key"
    - "handle"

# Properties for Kinetic Task
task:
  server: "http://localhost:8080/kinetic-task"
  credentials:
    username: "admin"
    password: "admin"
  oauth:
    endpoint_server:
    redirect_endpoint_server:
  api_access_key_description: "Request CE"
  api_access_key_identifier: "request-ce"

# Properties for Kinetic Bridgehub
bridgehub:
  server: "http://localhost:8080/kinetic-bridgehub"
  credentials:
    username: "admin"
    password: "admin"

# Properties for Kinetic Filehub
filehub:
  server: "http://localhost:8080/kinetic-filehub"
  credentials:
    username: "admin"
    password: "admin"

# Kinetic Data SMTP Info (Set on SMTP Handler)
smtp:
  server: "smtp.gmail.com"
  port: "25"
  tls: "true"
  username: ""
  password: ""

# Kinetic Task kinetic_request_ce_notification_template_send_v1 handler
notification_template_handler:
  smtp_server: "smtp.gmail.com"
  smtp_port: "25"
  smtp_tls: "true"
  smtp_username: ""
  smtp_password: ""
  smtp_from_address: ""
